# Generated by Django 5.0.4 on 2024-04-30 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='services_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='services_image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='services_title',
        ),
        migrations.AlterField(
            model_name='service',
            name='deadline',
            field=models.CharField(max_length=100, verbose_name='срок выполнения'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_services.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'запись на услугу',
                'verbose_name_plural': 'записи на услугу',
            },
        ),
    ]
